# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keyboard-ui.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 388)
        MainWindow.setStyleSheet("#bmsupport {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0,     stop:0 rgba(20, 20, 20, 255), stop:1 rgba(40, 40, 40, 1));\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0C7D16, stop:1 #21CF30);\n"
"    border: 1px solid gray;\n"
"    font: 20px;\n"
"    padding: 6px;\n"
"    min-width: 70;\n"
"    min-height: 20;\n"
"    max-width: 100;\n"
"    max-height: 100;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0C7D16, stop:1 #009E0D);\n"
"    border-style: outset;\n"
"    border-width: 4px;\n"
"    border-color: red;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0C7D16, stop:1 #31DF40);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0C7D16, stop:1 #009E0D);\n"
"    border-style: outset;\n"
"    border-width: 4px;\n"
"    border-color: red;\n"
"}\n"
"\n"
"QlineEdit {}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_2.addWidget(self.pushButton_20)
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_2.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_2.addWidget(self.pushButton_28)
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_2.addWidget(self.pushButton_23)
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_2.addWidget(self.pushButton_26)
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_2.addWidget(self.pushButton_25)
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_2.addWidget(self.pushButton_24)
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_2.addWidget(self.pushButton_22)
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_2.addWidget(self.pushButton_21)
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_2.addWidget(self.pushButton_19)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_2.addWidget(self.pushButton_18)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_2.addWidget(self.pushButton_17)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_2.addWidget(self.pushButton_16)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_2.addWidget(self.pushButton_15)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout.addWidget(self.pushButton_14)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout.addWidget(self.pushButton_12)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_54 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_54.setObjectName("pushButton_54")
        self.horizontalLayout_5.addWidget(self.pushButton_54)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_49 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_49.setObjectName("pushButton_49")
        self.horizontalLayout_4.addWidget(self.pushButton_49)
        self.pushButton_52 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_52.setObjectName("pushButton_52")
        self.horizontalLayout_4.addWidget(self.pushButton_52)
        self.pushButton_53 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_53.setObjectName("pushButton_53")
        self.horizontalLayout_4.addWidget(self.pushButton_53)
        self.pushButton_51 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_51.setObjectName("pushButton_51")
        self.horizontalLayout_4.addWidget(self.pushButton_51)
        self.pushButton_50 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_50.setObjectName("pushButton_50")
        self.horizontalLayout_4.addWidget(self.pushButton_50)
        self.pushButton_48 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_48.setObjectName("pushButton_48")
        self.horizontalLayout_4.addWidget(self.pushButton_48)
        self.pushButton_47 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_47.setObjectName("pushButton_47")
        self.horizontalLayout_4.addWidget(self.pushButton_47)
        self.pushButton_46 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_46.setObjectName("pushButton_46")
        self.horizontalLayout_4.addWidget(self.pushButton_46)
        self.pushButton_45 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_45.setObjectName("pushButton_45")
        self.horizontalLayout_4.addWidget(self.pushButton_45)
        self.pushButton_44 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_44.setObjectName("pushButton_44")
        self.horizontalLayout_4.addWidget(self.pushButton_44)
        self.pushButton_43 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_43.setObjectName("pushButton_43")
        self.horizontalLayout_4.addWidget(self.pushButton_43)
        self.pushButton_42 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_42.setObjectName("pushButton_42")
        self.horizontalLayout_4.addWidget(self.pushButton_42)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout_3.addWidget(self.pushButton_38)
        self.pushButton_41 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_41.setObjectName("pushButton_41")
        self.horizontalLayout_3.addWidget(self.pushButton_41)
        self.pushButton_40 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_40.setObjectName("pushButton_40")
        self.horizontalLayout_3.addWidget(self.pushButton_40)
        self.pushButton_39 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_3.addWidget(self.pushButton_39)
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_3.addWidget(self.pushButton_37)
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_3.addWidget(self.pushButton_36)
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_3.addWidget(self.pushButton_35)
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_3.addWidget(self.pushButton_34)
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_3.addWidget(self.pushButton_33)
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_3.addWidget(self.pushButton_32)
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_3.addWidget(self.pushButton_31)
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_3.addWidget(self.pushButton_30)
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_3.addWidget(self.pushButton_29)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_20.setText(_translate("MainWindow", "TAB"))
        self.pushButton_27.setText(_translate("MainWindow", "q"))
        self.pushButton_28.setText(_translate("MainWindow", "w"))
        self.pushButton_23.setText(_translate("MainWindow", "e"))
        self.pushButton_26.setText(_translate("MainWindow", "r"))
        self.pushButton_25.setText(_translate("MainWindow", "t"))
        self.pushButton_24.setText(_translate("MainWindow", "y"))
        self.pushButton_22.setText(_translate("MainWindow", "u"))
        self.pushButton_21.setText(_translate("MainWindow", "i"))
        self.pushButton_19.setText(_translate("MainWindow", "o"))
        self.pushButton_18.setText(_translate("MainWindow", "p"))
        self.pushButton_17.setText(_translate("MainWindow", "["))
        self.pushButton_16.setText(_translate("MainWindow", "]"))
        self.pushButton_15.setText(_translate("MainWindow", "\\"))
        self.pushButton_7.setText(_translate("MainWindow", "`"))
        self.pushButton_6.setText(_translate("MainWindow", "1"))
        self.pushButton_13.setText(_translate("MainWindow", "2"))
        self.pushButton_14.setText(_translate("MainWindow", "3"))
        self.pushButton_11.setText(_translate("MainWindow", "4"))
        self.pushButton_12.setText(_translate("MainWindow", "5"))
        self.pushButton_10.setText(_translate("MainWindow", "6"))
        self.pushButton_9.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_5.setText(_translate("MainWindow", "9"))
        self.pushButton_4.setText(_translate("MainWindow", "0"))
        self.pushButton_3.setText(_translate("MainWindow", "-"))
        self.pushButton_2.setText(_translate("MainWindow", "="))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.pushButton_54.setText(_translate("MainWindow", "SPACE"))
        self.pushButton_49.setText(_translate("MainWindow", "SHIFT"))
        self.pushButton_52.setText(_translate("MainWindow", "z"))
        self.pushButton_53.setText(_translate("MainWindow", "x"))
        self.pushButton_51.setText(_translate("MainWindow", "c"))
        self.pushButton_50.setText(_translate("MainWindow", "v"))
        self.pushButton_48.setText(_translate("MainWindow", "b"))
        self.pushButton_47.setText(_translate("MainWindow", "n"))
        self.pushButton_46.setText(_translate("MainWindow", "m"))
        self.pushButton_45.setText(_translate("MainWindow", ","))
        self.pushButton_44.setText(_translate("MainWindow", "."))
        self.pushButton_43.setText(_translate("MainWindow", "/"))
        self.pushButton_42.setText(_translate("MainWindow", "SHIFT"))
        self.pushButton_38.setText(_translate("MainWindow", "CAPS"))
        self.pushButton_41.setText(_translate("MainWindow", "a"))
        self.pushButton_40.setText(_translate("MainWindow", "s"))
        self.pushButton_39.setText(_translate("MainWindow", "d"))
        self.pushButton_37.setText(_translate("MainWindow", "f"))
        self.pushButton_36.setText(_translate("MainWindow", "g"))
        self.pushButton_35.setText(_translate("MainWindow", "h"))
        self.pushButton_34.setText(_translate("MainWindow", "j"))
        self.pushButton_33.setText(_translate("MainWindow", "k"))
        self.pushButton_32.setText(_translate("MainWindow", "l"))
        self.pushButton_31.setText(_translate("MainWindow", ";"))
        self.pushButton_30.setText(_translate("MainWindow", "\'"))
        self.pushButton_29.setText(_translate("MainWindow", "ENTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

