# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keyboard-ui.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 306)
        MainWindow.setStyleSheet("#MainWindow {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0,     stop:0 rgba(20, 20, 20, 255), stop:1 rgba(40, 40, 40, 1));\n"
"}\n"
"\n"
"#key_space { \n"
"    min-width: 400;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0C7D16, stop:1 #21CF30);\n"
"    border: 1px solid gray;\n"
"    font: 20px;\n"
"    padding: 6px;\n"
"    min-width: 40;\n"
"    min-height: 40;\n"
"    max-width: 200;\n"
"    max-height: 200;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0C7D16, stop:1 #009E0D);\n"
"    border-style: outset;\n"
"    border-width: 4px;\n"
"    border-color: red;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0C7D16, stop:1 #31DF40);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0C7D16, stop:1 #009E0D);\n"
"    border-style: outset;\n"
"    border-width: 4px;\n"
"    border-color: red;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_computer = QtWidgets.QLineEdit(self.centralwidget)
        self.text_computer.setObjectName("text_computer")
        self.verticalLayout.addWidget(self.text_computer)
        self.text_user = QtWidgets.QLineEdit(self.centralwidget)
        self.text_user.setObjectName("text_user")
        self.verticalLayout.addWidget(self.text_user)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.key_tab = QtWidgets.QPushButton(self.centralwidget)
        self.key_tab.setObjectName("key_tab")
        self.horizontalLayout_2.addWidget(self.key_tab)
        self.key_q = QtWidgets.QPushButton(self.centralwidget)
        self.key_q.setObjectName("key_q")
        self.horizontalLayout_2.addWidget(self.key_q)
        self.key_w = QtWidgets.QPushButton(self.centralwidget)
        self.key_w.setObjectName("key_w")
        self.horizontalLayout_2.addWidget(self.key_w)
        self.key_e = QtWidgets.QPushButton(self.centralwidget)
        self.key_e.setObjectName("key_e")
        self.horizontalLayout_2.addWidget(self.key_e)
        self.key_r = QtWidgets.QPushButton(self.centralwidget)
        self.key_r.setObjectName("key_r")
        self.horizontalLayout_2.addWidget(self.key_r)
        self.key_t = QtWidgets.QPushButton(self.centralwidget)
        self.key_t.setObjectName("key_t")
        self.horizontalLayout_2.addWidget(self.key_t)
        self.key_y = QtWidgets.QPushButton(self.centralwidget)
        self.key_y.setObjectName("key_y")
        self.horizontalLayout_2.addWidget(self.key_y)
        self.key_u = QtWidgets.QPushButton(self.centralwidget)
        self.key_u.setObjectName("key_u")
        self.horizontalLayout_2.addWidget(self.key_u)
        self.key_i = QtWidgets.QPushButton(self.centralwidget)
        self.key_i.setObjectName("key_i")
        self.horizontalLayout_2.addWidget(self.key_i)
        self.key_o = QtWidgets.QPushButton(self.centralwidget)
        self.key_o.setObjectName("key_o")
        self.horizontalLayout_2.addWidget(self.key_o)
        self.key_p = QtWidgets.QPushButton(self.centralwidget)
        self.key_p.setObjectName("key_p")
        self.horizontalLayout_2.addWidget(self.key_p)
        self.key_sqrbrkt_left = QtWidgets.QPushButton(self.centralwidget)
        self.key_sqrbrkt_left.setObjectName("key_sqrbrkt_left")
        self.horizontalLayout_2.addWidget(self.key_sqrbrkt_left)
        self.key_sqrbrkt_right = QtWidgets.QPushButton(self.centralwidget)
        self.key_sqrbrkt_right.setObjectName("key_sqrbrkt_right")
        self.horizontalLayout_2.addWidget(self.key_sqrbrkt_right)
        self.key_back_slash = QtWidgets.QPushButton(self.centralwidget)
        self.key_back_slash.setObjectName("key_back_slash")
        self.horizontalLayout_2.addWidget(self.key_back_slash)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.key_tilde = QtWidgets.QPushButton(self.centralwidget)
        self.key_tilde.setObjectName("key_tilde")
        self.horizontalLayout.addWidget(self.key_tilde)
        self.key_1 = QtWidgets.QPushButton(self.centralwidget)
        self.key_1.setObjectName("key_1")
        self.horizontalLayout.addWidget(self.key_1)
        self.key_2 = QtWidgets.QPushButton(self.centralwidget)
        self.key_2.setObjectName("key_2")
        self.horizontalLayout.addWidget(self.key_2)
        self.key_3 = QtWidgets.QPushButton(self.centralwidget)
        self.key_3.setObjectName("key_3")
        self.horizontalLayout.addWidget(self.key_3)
        self.key_4 = QtWidgets.QPushButton(self.centralwidget)
        self.key_4.setObjectName("key_4")
        self.horizontalLayout.addWidget(self.key_4)
        self.key_5 = QtWidgets.QPushButton(self.centralwidget)
        self.key_5.setObjectName("key_5")
        self.horizontalLayout.addWidget(self.key_5)
        self.key_6 = QtWidgets.QPushButton(self.centralwidget)
        self.key_6.setObjectName("key_6")
        self.horizontalLayout.addWidget(self.key_6)
        self.key_7 = QtWidgets.QPushButton(self.centralwidget)
        self.key_7.setObjectName("key_7")
        self.horizontalLayout.addWidget(self.key_7)
        self.key_8 = QtWidgets.QPushButton(self.centralwidget)
        self.key_8.setObjectName("key_8")
        self.horizontalLayout.addWidget(self.key_8)
        self.key_9 = QtWidgets.QPushButton(self.centralwidget)
        self.key_9.setObjectName("key_9")
        self.horizontalLayout.addWidget(self.key_9)
        self.key_0 = QtWidgets.QPushButton(self.centralwidget)
        self.key_0.setObjectName("key_0")
        self.horizontalLayout.addWidget(self.key_0)
        self.key_dash = QtWidgets.QPushButton(self.centralwidget)
        self.key_dash.setObjectName("key_dash")
        self.horizontalLayout.addWidget(self.key_dash)
        self.key_equals = QtWidgets.QPushButton(self.centralwidget)
        self.key_equals.setObjectName("key_equals")
        self.horizontalLayout.addWidget(self.key_equals)
        self.key_back = QtWidgets.QPushButton(self.centralwidget)
        self.key_back.setObjectName("key_back")
        self.horizontalLayout.addWidget(self.key_back)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.key_space = QtWidgets.QPushButton(self.centralwidget)
        self.key_space.setObjectName("key_space")
        self.horizontalLayout_5.addWidget(self.key_space)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.key_shift_left = QtWidgets.QPushButton(self.centralwidget)
        self.key_shift_left.setObjectName("key_shift_left")
        self.horizontalLayout_4.addWidget(self.key_shift_left)
        self.key_z = QtWidgets.QPushButton(self.centralwidget)
        self.key_z.setObjectName("key_z")
        self.horizontalLayout_4.addWidget(self.key_z)
        self.key_x = QtWidgets.QPushButton(self.centralwidget)
        self.key_x.setObjectName("key_x")
        self.horizontalLayout_4.addWidget(self.key_x)
        self.key_c = QtWidgets.QPushButton(self.centralwidget)
        self.key_c.setObjectName("key_c")
        self.horizontalLayout_4.addWidget(self.key_c)
        self.key_v = QtWidgets.QPushButton(self.centralwidget)
        self.key_v.setObjectName("key_v")
        self.horizontalLayout_4.addWidget(self.key_v)
        self.key_b = QtWidgets.QPushButton(self.centralwidget)
        self.key_b.setObjectName("key_b")
        self.horizontalLayout_4.addWidget(self.key_b)
        self.key_n = QtWidgets.QPushButton(self.centralwidget)
        self.key_n.setObjectName("key_n")
        self.horizontalLayout_4.addWidget(self.key_n)
        self.key_m = QtWidgets.QPushButton(self.centralwidget)
        self.key_m.setObjectName("key_m")
        self.horizontalLayout_4.addWidget(self.key_m)
        self.key_comma = QtWidgets.QPushButton(self.centralwidget)
        self.key_comma.setObjectName("key_comma")
        self.horizontalLayout_4.addWidget(self.key_comma)
        self.key_dot = QtWidgets.QPushButton(self.centralwidget)
        self.key_dot.setObjectName("key_dot")
        self.horizontalLayout_4.addWidget(self.key_dot)
        self.key_forward_slash = QtWidgets.QPushButton(self.centralwidget)
        self.key_forward_slash.setObjectName("key_forward_slash")
        self.horizontalLayout_4.addWidget(self.key_forward_slash)
        self.key_shift_right = QtWidgets.QPushButton(self.centralwidget)
        self.key_shift_right.setObjectName("key_shift_right")
        self.horizontalLayout_4.addWidget(self.key_shift_right)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.key_caps = QtWidgets.QPushButton(self.centralwidget)
        self.key_caps.setObjectName("key_caps")
        self.horizontalLayout_3.addWidget(self.key_caps)
        self.key_a = QtWidgets.QPushButton(self.centralwidget)
        self.key_a.setObjectName("key_a")
        self.horizontalLayout_3.addWidget(self.key_a)
        self.key_s = QtWidgets.QPushButton(self.centralwidget)
        self.key_s.setObjectName("key_s")
        self.horizontalLayout_3.addWidget(self.key_s)
        self.key_d = QtWidgets.QPushButton(self.centralwidget)
        self.key_d.setObjectName("key_d")
        self.horizontalLayout_3.addWidget(self.key_d)
        self.key_f = QtWidgets.QPushButton(self.centralwidget)
        self.key_f.setObjectName("key_f")
        self.horizontalLayout_3.addWidget(self.key_f)
        self.key_g = QtWidgets.QPushButton(self.centralwidget)
        self.key_g.setObjectName("key_g")
        self.horizontalLayout_3.addWidget(self.key_g)
        self.key_h = QtWidgets.QPushButton(self.centralwidget)
        self.key_h.setObjectName("key_h")
        self.horizontalLayout_3.addWidget(self.key_h)
        self.key_j = QtWidgets.QPushButton(self.centralwidget)
        self.key_j.setObjectName("key_j")
        self.horizontalLayout_3.addWidget(self.key_j)
        self.key_k = QtWidgets.QPushButton(self.centralwidget)
        self.key_k.setObjectName("key_k")
        self.horizontalLayout_3.addWidget(self.key_k)
        self.key_l = QtWidgets.QPushButton(self.centralwidget)
        self.key_l.setObjectName("key_l")
        self.horizontalLayout_3.addWidget(self.key_l)
        self.key_semicolon = QtWidgets.QPushButton(self.centralwidget)
        self.key_semicolon.setObjectName("key_semicolon")
        self.horizontalLayout_3.addWidget(self.key_semicolon)
        self.key_apostrophe = QtWidgets.QPushButton(self.centralwidget)
        self.key_apostrophe.setObjectName("key_apostrophe")
        self.horizontalLayout_3.addWidget(self.key_apostrophe)
        self.key_enter = QtWidgets.QPushButton(self.centralwidget)
        self.key_enter.setObjectName("key_enter")
        self.horizontalLayout_3.addWidget(self.key_enter)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.key_tab.setText(_translate("MainWindow", "TAB"))
        self.key_q.setText(_translate("MainWindow", "q"))
        self.key_w.setText(_translate("MainWindow", "w"))
        self.key_e.setText(_translate("MainWindow", "e"))
        self.key_r.setText(_translate("MainWindow", "r"))
        self.key_t.setText(_translate("MainWindow", "t"))
        self.key_y.setText(_translate("MainWindow", "y"))
        self.key_u.setText(_translate("MainWindow", "u"))
        self.key_i.setText(_translate("MainWindow", "i"))
        self.key_o.setText(_translate("MainWindow", "o"))
        self.key_p.setText(_translate("MainWindow", "p"))
        self.key_sqrbrkt_left.setText(_translate("MainWindow", "["))
        self.key_sqrbrkt_right.setText(_translate("MainWindow", "]"))
        self.key_back_slash.setText(_translate("MainWindow", "\\"))
        self.key_tilde.setText(_translate("MainWindow", "`"))
        self.key_1.setText(_translate("MainWindow", "1"))
        self.key_2.setText(_translate("MainWindow", "2"))
        self.key_3.setText(_translate("MainWindow", "3"))
        self.key_4.setText(_translate("MainWindow", "4"))
        self.key_5.setText(_translate("MainWindow", "5"))
        self.key_6.setText(_translate("MainWindow", "6"))
        self.key_7.setText(_translate("MainWindow", "7"))
        self.key_8.setText(_translate("MainWindow", "8"))
        self.key_9.setText(_translate("MainWindow", "9"))
        self.key_0.setText(_translate("MainWindow", "0"))
        self.key_dash.setText(_translate("MainWindow", "-"))
        self.key_equals.setText(_translate("MainWindow", "="))
        self.key_back.setText(_translate("MainWindow", "Back"))
        self.key_space.setText(_translate("MainWindow", "SPACE"))
        self.key_shift_left.setText(_translate("MainWindow", "SHIFT"))
        self.key_z.setText(_translate("MainWindow", "z"))
        self.key_x.setText(_translate("MainWindow", "x"))
        self.key_c.setText(_translate("MainWindow", "c"))
        self.key_v.setText(_translate("MainWindow", "v"))
        self.key_b.setText(_translate("MainWindow", "b"))
        self.key_n.setText(_translate("MainWindow", "n"))
        self.key_m.setText(_translate("MainWindow", "m"))
        self.key_comma.setText(_translate("MainWindow", ","))
        self.key_dot.setText(_translate("MainWindow", "."))
        self.key_forward_slash.setText(_translate("MainWindow", "/"))
        self.key_shift_right.setText(_translate("MainWindow", "SHIFT"))
        self.key_caps.setText(_translate("MainWindow", "CAPS"))
        self.key_a.setText(_translate("MainWindow", "a"))
        self.key_s.setText(_translate("MainWindow", "s"))
        self.key_d.setText(_translate("MainWindow", "d"))
        self.key_f.setText(_translate("MainWindow", "f"))
        self.key_g.setText(_translate("MainWindow", "g"))
        self.key_h.setText(_translate("MainWindow", "h"))
        self.key_j.setText(_translate("MainWindow", "j"))
        self.key_k.setText(_translate("MainWindow", "k"))
        self.key_l.setText(_translate("MainWindow", "l"))
        self.key_semicolon.setText(_translate("MainWindow", ";"))
        self.key_apostrophe.setText(_translate("MainWindow", "\'"))
        self.key_enter.setText(_translate("MainWindow", "ENTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

